### ISSUE TITLE
Użytkownik rejestruje się w aplikacji (happy path)

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-app/android#14]
Prośba o podanie numeru telefonu. Na stałe umieszczony jest przedrostek +48.
Po potwierdzeniu, użytkownik otrzymuje wiadomość SMS na podany numer i wpisuje 6-cyfrowy kod z wiadomości.

**Comment by shymmq** [comment]
Rozważaliście użycie nowego API [SMS Retriever](https://developers.google.com/identity/sms-retriever/user-consent/overview)? Myślę, że znacznie uprościłoby to proces logowania.

**Comment by jakublipinski** [comment]
@shymmq dodasz do tego nowe issue. Możliwe że nie uda się w `1.0` ale później chętnie. Może to zakodzisz?

**Comment by shymmq** [comment]
@jakublipinski Jasne, na pewno nie jest to priorytet. Już dodaje issue.

**Comment by jakublipinski** [comment]
Możemy zamknąć?
