### ISSUE TITLE
Historia spotkanych urządzeń jest szyfrowana na urządzeniu

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-app/android#28]

**Comment by AdvenamTacet** [comment]
Tytuł sugeruje szyfrowanie otrzymanych identyfikatorów już po ich otrzymaniu.
Czy dobrze to rozumiem? Jaki jest cel takiego szyfrowania?

**Comment by jakublipinski** [comment]
Tu chodzi o szyfrowanie historii spotkanych urządzeń (jak w temacie) w bazie na urządzeniu.

Chodzi o to żeby w przypadku w którym ktoś przejmie telefon nie mógł dostać się do danych i np. wysłać je na serwer w czyimś imieniu.

**Comment by mikolak** [comment]
@jakublipinski baza ma skonfigurowane szyfrowanie (#32)

**Comment by jakublipinski** [comment]
Yay. Dziękuję
