### ISSUE TITLE
Publiczne pull'e

### ISSUE THREAD

**Issue by YourFrog** [ProteGO-app/android#34]
Witam,

Czy ten projekt będzie całkowicie otwarty i można tworzyć pulle które będą przeglądane i ewentualnie mergowane do głównej gałęzi?

**Comment by jakublipinski** [comment]
Dzięki że chcesz się zaangażować. Będziemy przeglądać wszystkie PR. Aby mieć większą pewność, że PR wejdzie najlepiej zacząć od opisania zmian i uzgodnieania ich w `issue` albo wzięcia się za coś co jest już wyspecyfikowane.

**Comment by dzek69** [comment]
Jakiś README byłby mocno wskazany i w nim takie właśnie sprawy można by było opisać

**Comment by shymmq** [comment]
@dzek69 zobacz [ProteGO-app/specs](https://github.com/ProteGO-app/specs)

**Comment by dzek69** [comment]
@shymmq W tym repo dodałbym więc chociaż README z linkiem do tego

**Comment by jakublipinski** [comment]
Tutaj jest opis co zrobić abyśmy mogli przyjmować PRy: https://github.com/ProteGO-app/specs/blob/master/CONTRIBUTING.md#Programuj%C4%99-jak-mog%C4%99-pom%C3%B3c
