### ISSUE TITLE
Lokalny development aplikacji.

### ISSUE THREAD

**Issue by Tarvald** [ProteGO-app/android#36]
Jest jakiś opis w jaki sposób developować lokalnie aplikacje?

Próbowałem się zarejestrować po uruchomieniu aplikacji przez android studio w swoim telefonie, ale dostałem odpowiedz http 500 po wpisaniu kodu z SMS'a podczas rejestracji.

**Comment by shymmq** [comment]
Zmień build variant na debug, wtedy kod dostajesz w toastcie.
Swoją drogą mi kod z SMS normalnie przechodzi, może spróbuj teraz jeszcze raz? Pewnie akurat coś było grzebane na serwerze.

**Comment by AlexF0rtune** [comment]
Mi normalnie śmiga build debugowy :)

**Comment by Tarvald** [comment]
Wszystko działa. Dzięki :)
