### ISSUE TITLE
Komunikat w SMS. Brak polskiej litery "ó" w słowie "Twój"

### ISSUE THREAD

**Issue by tomaszmnich** [ProteGO-app/android#46]
**Opis błędu**

Brak polskiej litery "ó" w komunikacie SMS.

**Kroki**

1. Odbierz kod SMS

 **Środowisko**
 - Wersja środowiska: stg

**Comment by jakublipinski** [comment]
Duplicate: https://github.com/ProteGO-app/backend/issues/41
