### ISSUE TITLE
Link w README nie działa

### ISSUE THREAD

**Issue by mzgreen** [ProteGO-app/android#59]
W readme jest niedziałający link: https://github.com/orgs/ProteGO-app/projects/1

**Comment by Tarvald** [comment]
link nie działa.

Mógłbyś sprawdzić raz jeszcze?

**Comment by Tarvald** [comment]
Faktycznie link z readme "Projekt GH do śledzenia zadań" który prowadzi do "https://github.com/orgs/ProteGO-app/projects/1" nie działa.

**Comment by jakublipinski** [comment]
Już działa.
