### ISSUE TITLE
Obrazki na onboardingu są rozciągnięte

### ISSUE THREAD

**Issue by mzgreen** [ProteGO-app/android#77]
Na pierwszym ekranie jaki widzi  użytkownik obrazki są rozciągnięte, widać to zwłaszcza w landscape.
Rozwiązaniem problemu mogłoby być przygotowanie osobno zielonego tła oraz obrazka z osobą. Tło chyba jest już gotowe, nawet w formie wektorowej (użyte na splash screenie), wiec pozostaje sylwetka osoby.

![device-2020-04-07-105921](https://user-images.githubusercontent.com/6561747/78650743-9c9f6580-78bf-11ea-8992-d4ee55a3360a.png)

**Comment by jakublipinski** [comment]
Aplikacja dostępna będzie tylko w trybie pionowym. Wtedy problem zostanie rozwiązany. Zostawiam do tego czasu otwarte.
