### ISSUE TITLE
Możliwość dodania do sklepu F-Droid

### ISSUE THREAD

**Issue by Arusekk** [ProteGO-app/android#78]
**Opis prozypozycji rozwiązania**

Jeśli udałoby się uwzględnić możliwość użycia micro-G zamiast Google Play Services, oraz braku crashlytics w produkcyjnej kompilacji (lub jakaś jego wolna alternatywa), aplikacja może być dostępna w sklepie F-Droid (https://f-droid.org/).

**Dodatkowe informacje**

Zgłosiłem propozycję dodania aplikacji do tego sklepu tutaj:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6593

Można sprawdzić lokalnie, czy aplikacja buduje się poprawnie: [krok 1](https://gitlab.com/fdroid/fdroiddata/-/blob/master/README.md#quickstart) i [krok 2](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#building-it). Mnie wyskakuje tylko jeden błąd ([logi](https://pastebin.com/VgKThjcf)).

F-Droid jest sklepem z aplikacjami skompilowanymi w pełni ze źródeł. Daje dużo ciekawych możliwości użytkownikom. No i można przypiąć apce [ładną grafikę](https://f-droid.org/badge/get-it-on.png).

**Comment by mzgreen** [comment]
Orientujesz się jaki % użytkowników Androida w Polsce nie używa Google Play, a używa F-Droid?

**Comment by Arusekk** [comment]
Niezbyt, zapewne dosyć niski. Nie wymagam, żeby koniecznie to się stało, ale byłoby bardzo miło, zwłaszcza że na moim smartfonie (Sailfish OS) emulator androida nie jest w stanie uruchomić Google Play'a.

**Comment by jakublipinski** [comment]
Crashalitics nie będzie w produkcyjnej wersji. Wątpię aby Ministerstwo Cyfryzacji (wydawca ProteGO) publikowało w nieoficjalnym sklepie. Pozostają pewnie nieoficjalne buildy...

**Comment by Arusekk** [comment]
W tym sklepie wszystkie buildy są nieoficjalne. 🤔 Chciałem tylko wiedzieć, czy trudno by było to wspierać, bo sam nigdy nie pisałem aplikacji używającej usług google play.

**Comment by mimi89999** [comment]
Usługi Google Play też trzeba usunąć. Nie patrzyłem jeszcze na kod i nie wiem do czego są one wykorzystywane.

Co do samego umieszczenia aplikacji w F-Droidzie, to potrzebna jest tylko zgoda autora. Całość kodu oraz wszystkie używane biblioteki muszą być 100% FOSS.

**Comment by mimi89999** [comment]
`com.google.gms:google-services` jest w zależnościach, ale nie jest używany.
@jakublipinski Czy będzie on używany w przyszłości, czy można go usunąć?

**Comment by Arusekk** [comment]
Niemiecka oficjalna aplikacja rozważa to całkiem na poważnie: corona-warn-app/cwa-app-android#1483

Uważam, że warto wrócić do tematu (argumenty przedstawione tam są dość mocne).

**Comment by mimi89999** [comment]
Czy aplikacja nie staje się praktycznie bezużyteczna bez bibliotek usług Google?

**Comment by Arusekk** [comment]
> I saw corona-warn-app/cwa-app-android#477 and corona-warn-app/cwa-documentation#5, however, these were asked months ago.
The main reason for declining it was that the api is from Google and requires Google Play Services anyway. However, this is not the case anymore.
Since September 2020, the Exposure Notification API can be used without Google Play Services on Android, if you use microG, which is a 100% FLOSS replacement for these Google Play Services. The reason is microG added support for the API in v0.2.12.203315.

Usługi Google Play można zastąpić implementacją [microG](https://microg.org), niestety znam się na tym tylko na tyle, żeby wskazać podobny projekt, w którym występuje podobny problem. Jeśli dowiem się więcej, postaram się pomóc lepiej.

**Comment by Arusekk** [comment]
Tu znajduje się poprawiony fork oficjalnej niemieckiej aplikacji: https://f-droid.org/packages/de.corona.tracing/
